cornell array:
[
    {
        "comName": "Ruby-throated/Black-chinned Hummingbird",
        "howMany": 2,
        "lat": 30.24716,
        "lng": -97.74391,
        "locID": "L2342235",
        "locName": "austin, tx, blunn creek greenway",
        "locationPrivate": true,
        "obsDt": "2013-09-14 08:15",
        "obsReviewed": false,
        "obsValid": true,
        "sciName": "Archilochus colubris/alexandri"
    },
    {
        "comName": "Yellow Warbler",
        "howMany": 3,
        "lat": 30.24716,
        "lng": -97.74391,
        "locID": "L2342235",
        "locName": "austin, tx, blunn creek greenway",
        "locationPrivate": true,
        "obsDt": "2013-09-14 08:15",
        "obsReviewed": false,
        "obsValid": true,
        "sciName": "Setophaga petechia"
    },
    {
        "comName": "Baltimore Oriole",
        "howMany": 3,
        "lat": 30.24716,
        "lng": -97.74391,
        "locID": "L2342235",
        "locName": "austin, tx, blunn creek greenway",
        "locationPrivate": true,
        "obsDt": "2013-09-14 08:15",
        "obsReviewed": false,
        "obsValid": true,
        "sciName": "Icterus galbula"
    },
    {
        "comName": "Yellow-bellied Flycatcher",
        "howMany": 2,
        "lat": 30.24716,
        "lng": -97.74391,
        "locID": "L2342235",
        "locName": "austin, tx, blunn creek greenway",
        "locationPrivate": true,
        "obsDt": "2013-09-14 08:15",
        "obsReviewed": false,
        "obsValid": true,
        "sciName": "Empidonax flaviventris"
    },
    {
        "comName": "Black-crested Titmouse",
        "howMany": 2,
        "lat": 30.24716,
        "lng": -97.74391,
        "locID": "L2342235",
        "locName": "austin, tx, blunn creek greenway",
        "locationPrivate": true,
        "obsDt": "2013-09-14 08:15",
        "obsReviewed": false,
        "obsValid": true,
        "sciName": "Baeolophus atricristatus"
    },
    {
        "comName": "Blue Jay",
        "howMany": 12,
        "lat": 30.24716,
        "lng": -97.74391,
        "locID": "L2342235",
        "locName": "austin, tx, blunn creek greenway",
        "locationPrivate": true,
        "obsDt": "2013-09-14 08:15",
        "obsReviewed": false,
        "obsValid": true,
        "sciName": "Cyanocitta cristata"
    },
    {
        "comName": "Black-throated Green Warbler",
        "howMany": 1,
        "lat": 30.24716,
        "lng": -97.74391,
        "locID": "L2342235",
        "locName": "austin, tx, blunn creek greenway",
        "locationPrivate": true,
        "obsDt": "2013-09-14 08:15",
        "obsReviewed": false,
        "obsValid": true,
        "sciName": "Setophaga virens"
    },
    {
        "comName": "Blue-gray Gnatcatcher",
        "howMany": 1,
        "lat": 30.24716,
        "lng": -97.74391,
        "locID": "L2342235",
        "locName": "austin, tx, blunn creek greenway",
        "locationPrivate": true,
        "obsDt": "2013-09-14 08:15",
        "obsReviewed": false,
        "obsValid": true,
        "sciName": "Polioptila caerulea"
    },
    {
        "comName": "Canada Warbler",
        "howMany": 1,
        "lat": 30.24716,
        "lng": -97.74391,
        "locID": "L2342235",
        "locName": "austin, tx, blunn creek greenway",
        "locationPrivate": true,
        "obsDt": "2013-09-14 08:15",
        "obsReviewed": false,
        "obsValid": true,
        "sciName": "Cardellina canadensis"
    },
    {
        "comName": "Carolina Chickadee",
        "howMany": 4,
        "lat": 30.24716,
        "lng": -97.74391,
        "locID": "L2342235",
        "locName": "austin, tx, blunn creek greenway",
        "locationPrivate": true,
        "obsDt": "2013-09-14 08:15",
        "obsReviewed": false,
        "obsValid": true,
        "sciName": "Poecile carolinensis"
    },
    {
        "comName": "Carolina Wren",
        "howMany": 12,
        "lat": 30.24716,
        "lng": -97.74391,
        "locID": "L2342235",
        "locName": "austin, tx, blunn creek greenway",
        "locationPrivate": true,
        "obsDt": "2013-09-14 08:15",
        "obsReviewed": false,
        "obsValid": true,
        "sciName": "Thryothorus ludovicianus"
    },
    {
        "comName": "Chimney Swift",
        "howMany": 20,
        "lat": 30.24716,
        "lng": -97.74391,
        "locID": "L2342235",
        "locName": "austin, tx, blunn creek greenway",
        "locationPrivate": true,
        "obsDt": "2013-09-14 08:15",
        "obsReviewed": false,
        "obsValid": true,
        "sciName": "Chaetura pelagica"
    },
    {
        "comName": "Downy Woodpecker",
        "howMany": 2,
        "lat": 30.24716,
        "lng": -97.74391,
        "locID": "L2342235",
        "locName": "austin, tx, blunn creek greenway",
        "locationPrivate": true,
        "obsDt": "2013-09-14 08:15",
        "obsReviewed": false,
        "obsValid": true,
        "sciName": "Picoides pubescens"
    },
    {
        "comName": "Eastern Wood-Pewee",
        "howMany": 3,
        "lat": 30.24716,
        "lng": -97.74391,
        "locID": "L2342235",
        "locName": "austin, tx, blunn creek greenway",
        "locationPrivate": true,
        "obsDt": "2013-09-14 08:15",
        "obsReviewed": false,
        "obsValid": true,
        "sciName": "Contopus virens"
    },
    {
        "comName": "Empidonax sp.",
        "howMany": 2,
        "lat": 30.24716,
        "lng": -97.74391,
        "locID": "L2342235",
        "locName": "austin, tx, blunn creek greenway",
        "locationPrivate": true,
        "obsDt": "2013-09-14 08:15",
        "obsReviewed": false,
        "obsValid": true,
        "sciName": "Empidonax sp."
    },
    {
        "comName": "European Starling",
        "howMany": 3,
        "lat": 30.24716,
        "lng": -97.74391,
        "locID": "L2342235",
        "locName": "austin, tx, blunn creek greenway",
        "locationPrivate": true,
        "obsDt": "2013-09-14 08:15",
        "obsReviewed": false,
        "obsValid": true,
        "sciName": "Sturnus vulgaris"
    },
    {
        "comName": "Great Crested Flycatcher",
        "howMany": 2,
        "lat": 30.24716,
        "lng": -97.74391,
        "locID": "L2342235",
        "locName": "austin, tx, blunn creek greenway",
        "locationPrivate": true,
        "obsDt": "2013-09-14 08:15",
        "obsReviewed": false,
        "obsValid": true,
        "sciName": "Myiarchus crinitus"
    },
    {
        "comName": "Great-tailed Grackle",
        "howMany": 10,
        "lat": 30.24716,
        "lng": -97.74391,
        "locID": "L2342235",
        "locName": "austin, tx, blunn creek greenway",
        "locationPrivate": true,
        "obsDt": "2013-09-14 08:15",
        "obsReviewed": false,
        "obsValid": true,
        "sciName": "Quiscalus mexicanus"
    },
    {
        "comName": "House Finch",
        "howMany": 15,
        "lat": 30.24716,
        "lng": -97.74391,
        "locID": "L2342235",
        "locName": "austin, tx, blunn creek greenway",
        "locationPrivate": true,
        "obsDt": "2013-09-14 08:15",
        "obsReviewed": false,
        "obsValid": true,
        "sciName": "Haemorhous mexicanus"
    },
    {
        "comName": "House Sparrow",
        "howMany": 6,
        "lat": 30.24716,
        "lng": -97.74391,
        "locID": "L2342235",
        "locName": "austin, tx, blunn creek greenway",
        "locationPrivate": true,
        "obsDt": "2013-09-14 08:15",
        "obsReviewed": false,
        "obsValid": true,
        "sciName": "Passer domesticus"
    },
    {
        "comName": "Inca Dove",
        "howMany": 2,
        "lat": 30.24716,
        "lng": -97.74391,
        "locID": "L2342235",
        "locName": "austin, tx, blunn creek greenway",
        "locationPrivate": true,
        "obsDt": "2013-09-14 08:15",
        "obsReviewed": false,
        "obsValid": true,
        "sciName": "Columbina inca"
    },
    {
        "comName": "Least Flycatcher",
        "howMany": 1,
        "lat": 30.24716,
        "lng": -97.74391,
        "locID": "L2342235",
        "locName": "austin, tx, blunn creek greenway",
        "locationPrivate": true,
        "obsDt": "2013-09-14 08:15",
        "obsReviewed": false,
        "obsValid": true,
        "sciName": "Empidonax minimus"
    },
    {
        "comName": "Lesser Goldfinch",
        "howMany": 2,
        "lat": 30.24716,
        "lng": -97.74391,
        "locID": "L2342235",
        "locName": "austin, tx, blunn creek greenway",
        "locationPrivate": true,
        "obsDt": "2013-09-14 08:15",
        "obsReviewed": false,
        "obsValid": true,
        "sciName": "Spinus psaltria"
    },
    {
        "comName": "Louisiana Waterthrush",
        "howMany": 1,
        "lat": 30.24716,
        "lng": -97.74391,
        "locID": "L2342235",
        "locName": "austin, tx, blunn creek greenway",
        "locationPrivate": true,
        "obsDt": "2013-09-14 08:15",
        "obsReviewed": false,
        "obsValid": true,
        "sciName": "Parkesia motacilla"
    },
    {
        "comName": "Mourning Dove",
        "howMany": 1,
        "lat": 30.24716,
        "lng": -97.74391,
        "locID": "L2342235",
        "locName": "austin, tx, blunn creek greenway",
        "locationPrivate": true,
        "obsDt": "2013-09-14 08:15",
        "obsReviewed": false,
        "obsValid": true,
        "sciName": "Zenaida macroura"
    },
    {
        "comName": "Mourning Warbler",
        "howMany": 3,
        "lat": 30.24716,
        "lng": -97.74391,
        "locID": "L2342235",
        "locName": "austin, tx, blunn creek greenway",
        "locationPrivate": true,
        "obsDt": "2013-09-14 08:15",
        "obsReviewed": false,
        "obsValid": true,
        "sciName": "Geothlypis philadelphia"
    },
    {
        "comName": "Nashville Warbler",
        "howMany": 1,
        "lat": 30.24716,
        "lng": -97.74391,
        "locID": "L2342235",
        "locName": "austin, tx, blunn creek greenway",
        "locationPrivate": true,
        "obsDt": "2013-09-14 08:15",
        "obsReviewed": false,
        "obsValid": true,
        "sciName": "Oreothlypis ruficapilla"
    },
    {
        "comName": "Northern Cardinal",
        "howMany": 10,
        "lat": 30.24716,
        "lng": -97.74391,
        "locID": "L2342235",
        "locName": "austin, tx, blunn creek greenway",
        "locationPrivate": true,
        "obsDt": "2013-09-14 08:15",
        "obsReviewed": false,
        "obsValid": true,
        "sciName": "Cardinalis cardinalis"
    },
    {
        "comName": "Northern Mockingbird",
        "howMany": 3,
        "lat": 30.24716,
        "lng": -97.74391,
        "locID": "L2342235",
        "locName": "austin, tx, blunn creek greenway",
        "locationPrivate": true,
        "obsDt": "2013-09-14 08:15",
        "obsReviewed": false,
        "obsValid": true,
        "sciName": "Mimus polyglottos"
    },
    {
        "comName": "Red-bellied Woodpecker",
        "howMany": 3,
        "lat": 30.24716,
        "lng": -97.74391,
        "locID": "L2342235",
        "locName": "austin, tx, blunn creek greenway",
        "locationPrivate": true,
        "obsDt": "2013-09-14 08:15",
        "obsReviewed": false,
        "obsValid": true,
        "sciName": "Melanerpes carolinus"
    },
    {
        "comName": "Red-shouldered Hawk",
        "howMany": 1,
        "lat": 30.24716,
        "lng": -97.74391,
        "locID": "L2342235",
        "locName": "austin, tx, blunn creek greenway",
        "locationPrivate": true,
        "obsDt": "2013-09-14 08:15",
        "obsReviewed": false,
        "obsValid": true,
        "sciName": "Buteo lineatus"
    },
    {
        "comName": "Rock Pigeon",
        "howMany": 2,
        "lat": 30.24716,
        "lng": -97.74391,
        "locID": "L2342235",
        "locName": "austin, tx, blunn creek greenway",
        "locationPrivate": true,
        "obsDt": "2013-09-14 08:15",
        "obsReviewed": false,
        "obsValid": true,
        "sciName": "Columba livia"
    },
    {
        "comName": "Ruby-throated Hummingbird",
        "howMany": 1,
        "lat": 30.24716,
        "lng": -97.74391,
        "locID": "L2342235",
        "locName": "austin, tx, blunn creek greenway",
        "locationPrivate": true,
        "obsDt": "2013-09-14 08:15",
        "obsReviewed": false,
        "obsValid": true,
        "sciName": "Archilochus colubris"
    },
    {
        "comName": "Turkey Vulture",
        "howMany": 1,
        "lat": 30.24716,
        "lng": -97.74391,
        "locID": "L2342235",
        "locName": "austin, tx, blunn creek greenway",
        "locationPrivate": true,
        "obsDt": "2013-09-14 08:15",
        "obsReviewed": false,
        "obsValid": true,
        "sciName": "Cathartes aura"
    },
    {
        "comName": "White-eyed Vireo",
        "howMany": 2,
        "lat": 30.24716,
        "lng": -97.74391,
        "locID": "L2342235",
        "locName": "austin, tx, blunn creek greenway",
        "locationPrivate": true,
        "obsDt": "2013-09-14 08:15",
        "obsReviewed": false,
        "obsValid": true,
        "sciName": "Vireo griseus"
    },
    {
        "comName": "White-winged Dove",
        "howMany": 25,
        "lat": 30.24716,
        "lng": -97.74391,
        "locID": "L2342235",
        "locName": "austin, tx, blunn creek greenway",
        "locationPrivate": true,
        "obsDt": "2013-09-14 08:15",
        "obsReviewed": false,
        "obsValid": true,
        "sciName": "Zenaida asiatica"
    },
    {
        "comName": "Willow Flycatcher",
        "howMany": 2,
        "lat": 30.24716,
        "lng": -97.74391,
        "locID": "L2342235",
        "locName": "austin, tx, blunn creek greenway",
        "locationPrivate": true,
        "obsDt": "2013-09-14 08:15",
        "obsReviewed": false,
        "obsValid": true,
        "sciName": "Empidonax traillii"
    },
    {
        "comName": "Wilson's Warbler",
        "howMany": 4,
        "lat": 30.24716,
        "lng": -97.74391,
        "locID": "L2342235",
        "locName": "austin, tx, blunn creek greenway",
        "locationPrivate": true,
        "obsDt": "2013-09-14 08:15",
        "obsReviewed": false,
        "obsValid": true,
        "sciName": "Cardellina pusilla"
    },
    {
        "comName": "Common Nighthawk",
        "howMany": 5,
        "lat": 30.25589,
        "lng": -97.74591,
        "locID": "L2327478",
        "locName": "Riverside/Congress FS, 127 East Riverside Drive",
        "locationPrivate": true,
        "obsDt": "2013-09-13 19:45",
        "obsReviewed": false,
        "obsValid": true,
        "sciName": "Chordeiles minor"
    },
    {
        "comName": "Tufted x Black-crested Titmouse (hybrid)",
        "howMany": 1,
        "lat": 30.25084,
        "lng": -97.75993,
        "locID": "L1747758",
        "locName": "Becker Elementary School",
        "locationPrivate": true,
        "obsDt": "2013-09-07 19:00",
        "obsReviewed": false,
        "obsValid": true,
        "sciName": "Baeolophus bicolor x atricristatus"
    }
]

cornell test object:
[{
        "comName": "Baltimore Oriole",
        "howMany": 3,
        "lat": 30.24716,
        "lng": -97.74391,
        "locID": "L2342235",
        "locName": "austin, tx, blunn creek greenway",
        "locationPrivate": true,
        "obsDt": "2013-09-14 08:15",
        "obsReviewed": false,
        "obsValid": true,
        "sciName": "Icterus galbula"
    },
    {
        "comName": "Yellow-bellied Flycatcher",
        "howMany": 2,
        "lat": 30.24716,
        "lng": -97.74391,
        "locID": "L2342235",
        "locName": "austin, tx, blunn creek greenway",
        "locationPrivate": true,
        "obsDt": "2013-09-14 08:15",
        "obsReviewed": false,
        "obsValid": true,
        "sciName": "Empidonax flaviventris"
    },
    {
        "comName": "Black-crested Titmouse",
        "howMany": 2,
        "lat": 30.24716,
        "lng": -97.74391,
        "locID": "L2342235",
        "locName": "austin, tx, blunn creek greenway",
        "locationPrivate": true,
        "obsDt": "2013-09-14 08:15",
        "obsReviewed": false,
        "obsValid": true,
        "sciName": "Baeolophus atricristatus"
    },
    {
        "comName": "Blue Jay",
        "howMany": 12,
        "lat": 30.24716,
        "lng": -97.74391,
        "locID": "L2342235",
        "locName": "austin, tx, blunn creek greenway",
        "locationPrivate": true,
        "obsDt": "2013-09-14 08:15",
        "obsReviewed": false,
        "obsValid": true,
        "sciName": "Cyanocitta cristata"
    }]

flikr object
'{ "photos": { "page": 1, "pages": "533", "perpage": 1, "total": "533", 
    "photo": [
      { "id": "503934066", "owner": "10458155@N00", "secret": "bfbcb366c9", "server": "222", "farm": 1, "title": "Eastern Wood-Pewee", "ispublic": 1, "isfriend": 0, "isfamily": 0 }
    ] }, "stat": "ok" }'

get_list output:
[
        {"comName"=>"Baltimore Oriole", "sciName"=>"Icterus galbula"},
        {"comName"=>"Yellow-bellied Flycatcher", "sciName"=>"Empidonax flaviventris"},
        {"comName"=>"Common Nighthawk", "sciName"=>"Chordeiles minor"}]    